update request
I was running into [this issue](https://github.com/request/request/issues/1522) when trying to do a ```forms.find```.  Updating request fixes my issue, although I have not tested all of the fulcrum-node methods.

```
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
```